[2025-05-24T09:17:52.658+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T09:17:05.548015+00:00 [queued]>
[2025-05-24T09:17:53.189+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T09:17:05.548015+00:00 [queued]>
[2025-05-24T09:17:53.198+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T09:17:53.391+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_contacts> on 2025-05-24 09:17:05.548015+00:00
[2025-05-24T09:17:53.458+0000] {standard_task_runner.py:60} INFO - Started process 1630 to run task
[2025-05-24T09:17:53.561+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'validate_contacts', 'manual__2025-05-24T09:17:05.548015+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp_rv5_y32']
[2025-05-24T09:17:53.639+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask validate_contacts
[2025-05-24T09:17:54.512+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T09:17:05.548015+00:00 [running]> on host e6492150ec46
[2025-05-24T09:17:55.917+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T09:17:05.548015+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T09:17:05.548015+00:00'
[2025-05-24T09:17:55.924+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-24T09:17:56.488+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | schema_format = FAIL
[2025-05-24T09:17:56.934+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | file-level = FAIL
[2025-05-24T09:17:56.949+0000] {data_validation.py:31} WARNING - Quarantining invalid rows for: contacts_2025-05-24.csv
[2025-05-24T09:17:57.431+0000] {metadata.py:158} INFO - üîë Logged DQ signature for contacts_2025-05-24.csv: 
[2025-05-24T09:17:57.756+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | contacts = FAIL
[2025-05-24T09:17:58.136+0000] {metadata.py:107} INFO - üìù Logged stage 'validated' for contacts_2025-05-24.csv at 2025-05-24T09:17:57.762204
[2025-05-24T09:17:58.152+0000] {utils.py:52} INFO - task_metrics
[2025-05-24T09:17:58.176+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-24T09:17:58.191+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T09:17:58.270+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=validate_contacts, execution_date=20250524T091705, start_date=20250524T091753, end_date=20250524T091758
[2025-05-24T09:17:58.885+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T09:17:59.010+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
