[2025-05-24T07:24:00.413+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:24:00.486+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:24:00.490+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T07:24:00.631+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_website_activity> on 2025-05-23 00:00:00+00:00
[2025-05-24T07:24:00.647+0000] {standard_task_runner.py:60} INFO - Started process 641 to run task
[2025-05-24T07:24:00.670+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'generate_website_activity', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp1t96ii77']
[2025-05-24T07:24:00.687+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask generate_website_activity
[2025-05-24T07:24:01.070+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [running]> on host fcb3825e40cf
[2025-05-24T07:24:01.595+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_website_activity' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T07:24:01.659+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Generate Website Activity
[2025-05-24T07:24:01.755+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_pipeline_dag.py", line 26, in _wrapped
    fn(**kwargs)
TypeError: generate_website_activity_if_needed() got an unexpected keyword argument 'conf'
[2025-05-24T07:24:01.978+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=marketing_data_pipeline, task_id=generate_website_activity, execution_date=20250523T000000, start_date=20250524T072400, end_date=20250524T072401
[2025-05-24T07:24:02.195+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task generate_website_activity (generate_website_activity_if_needed() got an unexpected keyword argument 'conf'; 641)
[2025-05-24T07:24:02.690+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-24T07:24:03.128+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T07:26:02.320+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:26:02.359+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:26:02.365+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T07:26:02.420+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_website_activity> on 2025-05-23 00:00:00+00:00
[2025-05-24T07:26:02.445+0000] {standard_task_runner.py:60} INFO - Started process 694 to run task
[2025-05-24T07:26:02.461+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'generate_website_activity', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmpd41exgo3']
[2025-05-24T07:26:02.466+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask generate_website_activity
[2025-05-24T07:26:02.828+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [running]> on host fcb3825e40cf
[2025-05-24T07:26:03.849+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_website_activity' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T07:26:03.864+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Generate Website Activity
[2025-05-24T07:26:03.960+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_pipeline_dag.py", line 26, in _wrapped
    fn(**kwargs)
TypeError: generate_website_activity_if_needed() got an unexpected keyword argument 'conf'
[2025-05-24T07:26:04.085+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=marketing_data_pipeline, task_id=generate_website_activity, execution_date=20250523T000000, start_date=20250524T072602, end_date=20250524T072604
[2025-05-24T07:26:04.265+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task generate_website_activity (generate_website_activity_if_needed() got an unexpected keyword argument 'conf'; 694)
[2025-05-24T07:26:04.338+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-24T07:26:04.642+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T08:18:27.980+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T08:18:28.045+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T08:18:28.066+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T08:18:28.179+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_website_activity> on 2025-05-23 00:00:00+00:00
[2025-05-24T08:18:28.252+0000] {standard_task_runner.py:60} INFO - Started process 318 to run task
[2025-05-24T08:18:28.353+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'generate_website_activity', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmpwc0u0mob']
[2025-05-24T08:18:28.472+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask generate_website_activity
[2025-05-24T08:18:29.449+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [running]> on host e6492150ec46
[2025-05-24T08:18:30.568+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_website_activity' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T08:18:30.576+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Generate Website Activity
[2025-05-24T08:18:37.769+0000] {data_generation.py:117} INFO - ‚úÖ website_activity_2025-05-23.json file generated
[2025-05-24T08:18:38.700+0000] {metadata.py:107} INFO - üìù Logged stage 'generated' for website_activity_2025-05-23.json at 2025-05-24T08:18:38.002603
[2025-05-24T08:18:38.723+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Generate Website Activity
[2025-05-24T08:18:38.735+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T08:18:38.807+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=generate_website_activity, execution_date=20250523T000000, start_date=20250524T081828, end_date=20250524T081838
[2025-05-24T08:18:39.772+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T08:18:39.950+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-24T10:16:57.231+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T10:16:57.328+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T10:16:57.330+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T10:16:57.507+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_website_activity> on 2025-05-23 00:00:00+00:00
[2025-05-24T10:16:57.518+0000] {standard_task_runner.py:60} INFO - Started process 345 to run task
[2025-05-24T10:16:57.528+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'generate_website_activity', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp_u84n5rr']
[2025-05-24T10:16:57.532+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask generate_website_activity
[2025-05-24T10:17:05.678+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.generate_website_activity scheduled__2025-05-23T00:00:00+00:00 [running]> on host 8c3b47b76f3b
[2025-05-24T10:17:11.725+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_website_activity' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T10:17:11.736+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Generate Website Activity
[2025-05-24T10:17:14.575+0000] {data_generation.py:117} INFO - ‚úÖ website_activity_2025-05-23.json file generated
[2025-05-24T10:17:15.032+0000] {metadata.py:107} INFO - üìù Logged stage 'generated' for website_activity_2025-05-23.json at 2025-05-24T10:17:14.579936
[2025-05-24T10:17:15.036+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Generate Website Activity
[2025-05-24T10:17:15.039+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T10:17:15.263+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=generate_website_activity, execution_date=20250523T000000, start_date=20250524T101657, end_date=20250524T101715
[2025-05-24T10:17:16.789+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T10:17:17.287+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
