[2025-05-25T19:09:36.358+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_marts manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T19:09:36.412+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_marts manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T19:09:36.442+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-05-25T19:09:36.552+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run.dbt_run_marts> on 2025-05-25 16:25:47.685943+00:00
[2025-05-25T19:09:36.585+0000] {standard_task_runner.py:60} INFO - Started process 19968 to run task
[2025-05-25T19:09:36.595+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_marketing_data_pipeline', 'dbt_run.dbt_run_marts', 'manual__2025-05-25T16:25:47.685943+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpez2nrkg_']
[2025-05-25T19:09:36.631+0000] {standard_task_runner.py:88} INFO - Job 136: Subtask dbt_run.dbt_run_marts
[2025-05-25T19:09:36.921+0000] {task_command.py:423} INFO - Running <TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_marts manual__2025-05-25T16:25:47.685943+00:00 [running]> on host fe289fe396bd
[2025-05-25T19:09:37.168+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='final_marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run.dbt_run_marts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T16:25:47.685943+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T16:25:47.685943+00:00'
[2025-05-25T19:09:37.172+0000] {test.py:39} INFO - ‚ñ∂Ô∏è Starting task: Run mart models
[2025-05-25T19:09:37.189+0000] {utils.py:64} INFO - Running dbt command: cd /opt/dbt/marketing_pipeline && dbt run --models marts --vars '{"batch_date": "2025-05-25"}'
[2025-05-25T19:09:45.384+0000] {utils.py:73} INFO - [0m19:09:45  Running with dbt=1.9.4
[2025-05-25T19:09:48.617+0000] {utils.py:73} INFO - [0m19:09:48  Registered adapter: snowflake=1.9.4
[2025-05-25T19:09:55.895+0000] {utils.py:73} INFO - [0m19:09:55  Found 12 models, 79 data tests, 6 sources, 479 macros
[2025-05-25T19:09:55.910+0000] {utils.py:73} INFO - [0m19:09:55
[2025-05-25T19:09:55.918+0000] {utils.py:73} INFO - [0m19:09:55  Concurrency: 4 threads (target='dev')
[2025-05-25T19:09:55.924+0000] {utils.py:73} INFO - [0m19:09:55
[2025-05-25T19:09:58.117+0000] {utils.py:73} INFO - [0m19:09:58  1 of 6 START sql incremental model MART.mart_campaigns ......................... [RUN]
[2025-05-25T19:09:58.123+0000] {utils.py:73} INFO - [0m19:09:58  2 of 6 START sql incremental model MART.mart_contacts .......................... [RUN]
[2025-05-25T19:09:58.128+0000] {utils.py:73} INFO - [0m19:09:58  3 of 6 START sql incremental model MART.mart_form_fills ........................ [RUN]
[2025-05-25T19:09:58.132+0000] {utils.py:73} INFO - [0m19:09:58  4 of 6 START sql incremental model MART.mart_forms ............................. [RUN]
[2025-05-25T19:10:00.749+0000] {utils.py:73} INFO - [0m19:10:00  2 of 6 OK created sql incremental model MART.mart_contacts ..................... [[32mSUCCESS 1[0m in 2.60s]
[2025-05-25T19:10:00.804+0000] {utils.py:73} INFO - [0m19:10:00  5 of 6 START sql incremental model MART.mart_pages ............................. [RUN]
[2025-05-25T19:10:01.910+0000] {utils.py:73} INFO - [0m19:10:01  1 of 6 OK created sql incremental model MART.mart_campaigns .................... [[32mSUCCESS 3[0m in 3.77s]
[2025-05-25T19:10:01.962+0000] {utils.py:73} INFO - [0m19:10:01  6 of 6 START sql incremental model MART.mart_website_activity .................. [RUN]
[2025-05-25T19:10:02.233+0000] {utils.py:73} INFO - [0m19:10:02  3 of 6 ERROR creating sql incremental model MART.mart_form_fills ............... [[31mERROR[0m in 4.09s]
[2025-05-25T19:10:02.289+0000] {utils.py:73} INFO - [0m19:10:02  5 of 6 ERROR creating sql incremental model MART.mart_pages .................... [[31mERROR[0m in 1.48s]
[2025-05-25T19:10:02.415+0000] {utils.py:73} INFO - [0m19:10:02  4 of 6 OK created sql incremental model MART.mart_forms ........................ [[32mSUCCESS 4[0m in 4.27s]
[2025-05-25T19:10:04.128+0000] {utils.py:73} INFO - [0m19:10:04  6 of 6 OK created sql incremental model MART.mart_website_activity ............. [[32mSUCCESS 1000[0m in 2.15s]
[2025-05-25T19:10:05.016+0000] {utils.py:73} INFO - [0m19:10:05
[2025-05-25T19:10:05.022+0000] {utils.py:73} INFO - [0m19:10:05  Finished running 6 incremental models in 0 hours 0 minutes and 9.09 seconds (9.09s).
[2025-05-25T19:10:05.272+0000] {utils.py:73} INFO - [0m19:10:05
[2025-05-25T19:10:05.280+0000] {utils.py:73} INFO - [0m19:10:05  [31mCompleted with 2 errors, 0 partial successes, and 0 warnings:[0m
[2025-05-25T19:10:05.285+0000] {utils.py:73} INFO - [0m19:10:05
[2025-05-25T19:10:05.291+0000] {utils.py:73} INFO - [0m19:10:05    Database Error in model mart_form_fills (models/marts/mart_form_fills.sql)
[2025-05-25T19:10:05.295+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T19:10:05.299+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T19:10:05.305+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/marts/mart_form_fills.sql
[2025-05-25T19:10:05.310+0000] {utils.py:73} INFO - [0m19:10:05
[2025-05-25T19:10:05.315+0000] {utils.py:73} INFO - [0m19:10:05    Database Error in model mart_pages (models/marts/mart_pages.sql)
[2025-05-25T19:10:05.322+0000] {utils.py:73} INFO - 000904 (42000): SQL compilation error: error line 3 at position 13
[2025-05-25T19:10:05.326+0000] {utils.py:73} INFO - invalid identifier 'DBT_INTERNAL_SOURCE.PAGE_ID'
[2025-05-25T19:10:05.331+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/marts/mart_pages.sql
[2025-05-25T19:10:05.339+0000] {utils.py:73} INFO - [0m19:10:05
[2025-05-25T19:10:05.346+0000] {utils.py:73} INFO - [0m19:10:05  Done. PASS=4 WARN=0 ERROR=2 SKIP=0 TOTAL=6
[2025-05-25T19:10:06.231+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 77, in run_dbt
    raise RuntimeError(f"dbt command failed with exit code {return_code}")
RuntimeError: dbt command failed with exit code 1
[2025-05-25T19:10:06.279+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=final_marketing_data_pipeline, task_id=dbt_run.dbt_run_marts, execution_date=20250525T162547, start_date=20250525T190936, end_date=20250525T191006
[2025-05-25T19:10:06.306+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 136 for task dbt_run.dbt_run_marts (dbt command failed with exit code 1; 19968)
[2025-05-25T19:10:06.352+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-25T19:10:06.415+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
