[2025-05-25T19:39:30.283+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-25T19:37:32.889912+00:00 [queued]>
[2025-05-25T19:39:30.304+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-25T19:37:32.889912+00:00 [queued]>
[2025-05-25T19:39:30.305+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-25T19:39:32.391+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_facts.validate_contacts> on 2025-05-25 19:37:32.889912+00:00
[2025-05-25T19:39:32.403+0000] {standard_task_runner.py:60} INFO - Started process 20662 to run task
[2025-05-25T19:39:32.412+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'validate_facts.validate_contacts', 'manual__2025-05-25T19:37:32.889912+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmp21t9gvrv']
[2025-05-25T19:39:32.416+0000] {standard_task_runner.py:88} INFO - Job 150: Subtask validate_facts.validate_contacts
[2025-05-25T19:39:33.175+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-25T19:37:32.889912+00:00 [running]> on host fe289fe396bd
[2025-05-25T19:39:33.942+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='validate_facts.validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T19:37:32.889912+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T19:37:32.889912+00:00'
[2025-05-25T19:39:33.949+0000] {Marketing_Data_Pipeline.py:39} INFO - ▶️ Starting task: Validate Contacts
[2025-05-25T19:39:34.161+0000] {data_validation.py:228} INFO - ⏩ Already validated: contacts_2025-05-25.csv
[2025-05-25T19:39:34.166+0000] {utils.py:55} INFO - task_metrics
[2025-05-25T19:39:34.174+0000] {Marketing_Data_Pipeline.py:41} INFO - ✅ Completed task: Validate Contacts
[2025-05-25T19:39:34.180+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-25T19:39:34.231+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Marketing_Data_Pipeline, task_id=validate_facts.validate_contacts, execution_date=20250525T193732, start_date=20250525T193930, end_date=20250525T193934
[2025-05-25T19:39:34.315+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-25T19:39:34.474+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
