[2025-05-26T00:00:48.342+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts scheduled__2025-05-25T00:00:00+00:00 [queued]>
[2025-05-26T00:00:48.396+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts scheduled__2025-05-25T00:00:00+00:00 [queued]>
[2025-05-26T00:00:48.408+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-26T00:00:48.491+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_facts.validate_contacts> on 2025-05-25 00:00:00+00:00
[2025-05-26T00:00:48.509+0000] {standard_task_runner.py:60} INFO - Started process 27106 to run task
[2025-05-26T00:00:48.524+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'validate_facts.validate_contacts', 'scheduled__2025-05-25T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmpqj37tijj']
[2025-05-26T00:00:48.532+0000] {standard_task_runner.py:88} INFO - Job 175: Subtask validate_facts.validate_contacts
[2025-05-26T00:00:48.830+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts scheduled__2025-05-25T00:00:00+00:00 [running]> on host fe289fe396bd
[2025-05-26T00:00:49.194+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='validate_facts.validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-25T00:00:00+00:00'
[2025-05-26T00:00:49.201+0000] {Marketing_Data_Pipeline.py:39} INFO - ▶️ Starting task: Validate Contacts
[2025-05-26T00:00:49.230+0000] {data_validation.py:228} INFO - ⏩ Already validated: contacts_2025-05-25.csv
[2025-05-26T00:00:49.235+0000] {utils.py:56} INFO - task_metrics
[2025-05-26T00:00:49.241+0000] {Marketing_Data_Pipeline.py:41} INFO - ✅ Completed task: Validate Contacts
[2025-05-26T00:00:49.245+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-26T00:00:49.299+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Marketing_Data_Pipeline, task_id=validate_facts.validate_contacts, execution_date=20250525T000000, start_date=20250526T000048, end_date=20250526T000049
[2025-05-26T00:00:49.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-26T00:00:49.540+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
