[2025-05-25T20:00:40.721+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.dbt_run.dbt_test manual__2025-05-25T19:37:32.889912+00:00 [queued]>
[2025-05-25T20:00:40.759+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.dbt_run.dbt_test manual__2025-05-25T19:37:32.889912+00:00 [queued]>
[2025-05-25T20:00:40.763+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-25T20:00:40.823+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run.dbt_test> on 2025-05-25 19:37:32.889912+00:00
[2025-05-25T20:00:40.840+0000] {standard_task_runner.py:60} INFO - Started process 21238 to run task
[2025-05-25T20:00:40.851+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'dbt_run.dbt_test', 'manual__2025-05-25T19:37:32.889912+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmpqq5fm4hp']
[2025-05-25T20:00:40.860+0000] {standard_task_runner.py:88} INFO - Job 160: Subtask dbt_run.dbt_test
[2025-05-25T20:00:41.174+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.dbt_run.dbt_test manual__2025-05-25T19:37:32.889912+00:00 [running]> on host fe289fe396bd
[2025-05-25T20:00:41.842+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='dbt_run.dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T19:37:32.889912+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T19:37:32.889912+00:00'
[2025-05-25T20:00:41.852+0000] {Marketing_Data_Pipeline.py:39} INFO - ‚ñ∂Ô∏è Starting task: Run all dbt tests
[2025-05-25T20:00:41.867+0000] {utils.py:91} INFO - Running dbt tests: cd /opt/dbt/marketing_pipeline && dbt test 
[2025-05-25T20:00:41.871+0000] {utils.py:65} INFO - Running dbt command: cd /opt/dbt/marketing_pipeline && dbt test 
[2025-05-25T20:00:41.882+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Marketing_Data_Pipeline.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 93, in run_dbt_test
    run_dbt(cmd)
  File "/opt/airflow/scripts/utils.py", line 73, in run_dbt
    full_log = process.stdout + process.stderr
TypeError: unsupported operand type(s) for +: '_io.TextIOWrapper' and 'NoneType'
[2025-05-25T20:00:42.024+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Marketing_Data_Pipeline, task_id=dbt_run.dbt_test, execution_date=20250525T193732, start_date=20250525T200040, end_date=20250525T200042
[2025-05-25T20:00:42.102+0000] {email_notification.py:58} WARNING - üìß Sending generic failure email [Airflow] Failure in Marketing_Data_Pipeline.dbt_run.dbt_test (Attempt 3/2)
[2025-05-25T20:00:42.206+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-05-25T20:00:42.223+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-05-25T20:00:43.800+0000] {email.py:281} INFO - Sent an alert email to ['yashbhawsar872@gmail.com']
[2025-05-25T20:00:45.365+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 160 for task dbt_run.dbt_test (unsupported operand type(s) for +: '_io.TextIOWrapper' and 'NoneType'; 21238)
[2025-05-25T20:00:45.410+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-25T20:00:45.506+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
