[2025-05-24T08:18:49.561+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T08:18:49.655+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T08:18:49.665+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T08:18:49.881+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_contacts> on 2025-05-23 00:00:00+00:00
[2025-05-24T08:18:49.932+0000] {standard_task_runner.py:60} INFO - Started process 336 to run task
[2025-05-24T08:18:49.958+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'validate_contacts', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmpgoe5d517']
[2025-05-24T08:18:49.977+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask validate_contacts
[2025-05-24T08:18:50.454+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.validate_contacts scheduled__2025-05-23T00:00:00+00:00 [running]> on host e6492150ec46
[2025-05-24T08:18:51.037+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T08:18:51.059+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-24T08:18:52.128+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-23.csv | schema_format = FAIL
[2025-05-24T08:18:52.547+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-23.csv | file-level = FAIL
[2025-05-24T08:18:52.569+0000] {data_validation.py:31} WARNING - Quarantining invalid rows for: contacts_2025-05-23.csv
[2025-05-24T08:18:54.604+0000] {metadata.py:158} INFO - üîë Logged DQ signature for contacts_2025-05-23.csv: 
[2025-05-24T08:18:54.662+0000] {utils.py:52} INFO - task_metrics
[2025-05-24T08:18:54.685+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-24T08:18:54.720+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T08:18:54.804+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=validate_contacts, execution_date=20250523T000000, start_date=20250524T081849, end_date=20250524T081854
[2025-05-24T08:18:55.233+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T08:18:55.510+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T10:17:52.674+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T10:17:52.716+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T10:17:52.718+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T10:17:52.794+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_contacts> on 2025-05-23 00:00:00+00:00
[2025-05-24T10:17:52.811+0000] {standard_task_runner.py:60} INFO - Started process 364 to run task
[2025-05-24T10:17:52.828+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'validate_contacts', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmpq_oyls71']
[2025-05-24T10:17:52.832+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask validate_contacts
[2025-05-24T10:17:53.066+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.validate_contacts scheduled__2025-05-23T00:00:00+00:00 [running]> on host 8c3b47b76f3b
[2025-05-24T10:17:53.670+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T10:17:53.685+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-24T10:17:54.083+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-23.csv | schema_format = PASS
[2025-05-24T10:17:56.200+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-23.csv | freshness = PASS
[2025-05-24T10:17:58.988+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-23.csv | row_count = PASS
[2025-05-24T10:18:00.699+0000] {metadata.py:158} INFO - üîë Logged DQ signature for contacts_2025-05-23.csv: 
[2025-05-24T10:18:07.617+0000] {metadata.py:138} INFO - üß™ DQ Check logged: contacts_2025-05-23.csv | contacts = PASS
[2025-05-24T10:18:07.916+0000] {metadata.py:107} INFO - üìù Logged stage 'validated' for contacts_2025-05-23.csv at 2025-05-24T10:18:07.634384
[2025-05-24T10:18:08.031+0000] {utils.py:52} INFO - task_metrics
[2025-05-24T10:18:08.091+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-24T10:18:08.140+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T10:18:08.237+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=validate_contacts, execution_date=20250523T000000, start_date=20250524T101752, end_date=20250524T101808
[2025-05-24T10:18:08.491+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T10:18:08.808+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
