[2025-05-25T17:42:10.328+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T17:42:10.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T17:42:10.370+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 5
[2025-05-25T17:42:10.439+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run.dbt_run_staging> on 2025-05-25 16:25:47.685943+00:00
[2025-05-25T17:42:10.468+0000] {standard_task_runner.py:60} INFO - Started process 17937 to run task
[2025-05-25T17:42:10.476+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_marketing_data_pipeline', 'dbt_run.dbt_run_staging', 'manual__2025-05-25T16:25:47.685943+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpggqkwl9r']
[2025-05-25T17:42:10.509+0000] {standard_task_runner.py:88} INFO - Job 131: Subtask dbt_run.dbt_run_staging
[2025-05-25T17:42:10.824+0000] {task_command.py:423} INFO - Running <TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [running]> on host fe289fe396bd
[2025-05-25T17:42:11.094+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='final_marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run.dbt_run_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T16:25:47.685943+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T16:25:47.685943+00:00'
[2025-05-25T17:42:11.098+0000] {test.py:39} INFO - ‚ñ∂Ô∏è Starting task: Run staging models
[2025-05-25T17:42:11.138+0000] {utils.py:64} INFO - Running dbt command: cd /opt/dbt/marketing_pipeline && dbt run --models staging --vars '{"batch_date": "2025-05-25"}'
[2025-05-25T17:42:33.082+0000] {utils.py:73} INFO - [0m17:42:33  Running with dbt=1.9.4
[2025-05-25T17:42:39.572+0000] {utils.py:73} INFO - [0m17:42:39  Registered adapter: snowflake=1.9.4
[2025-05-25T17:43:19.003+0000] {utils.py:73} INFO - [0m17:43:19  Found 12 models, 79 data tests, 6 sources, 479 macros
[2025-05-25T17:43:19.039+0000] {utils.py:73} INFO - [0m17:43:19
[2025-05-25T17:43:19.051+0000] {utils.py:73} INFO - [0m17:43:19  Concurrency: 4 threads (target='dev')
[2025-05-25T17:43:19.058+0000] {utils.py:73} INFO - [0m17:43:19
[2025-05-25T17:43:25.199+0000] {utils.py:73} INFO - [0m17:43:25  1 of 6 START sql incremental model STG.stg_campaigns ........................... [RUN]
[2025-05-25T17:43:25.204+0000] {utils.py:73} INFO - [0m17:43:25  2 of 6 START sql incremental model STG.stg_contacts ............................ [RUN]
[2025-05-25T17:43:25.215+0000] {utils.py:73} INFO - [0m17:43:25  3 of 6 START sql incremental model STG.stg_form_fills .......................... [RUN]
[2025-05-25T17:43:25.222+0000] {utils.py:73} INFO - [0m17:43:25  4 of 6 START sql incremental model STG.stg_forms ............................... [RUN]
[2025-05-25T17:43:29.022+0000] {utils.py:73} INFO - [0m17:43:29  4 of 6 ERROR creating sql incremental model STG.stg_forms ...................... [[31mERROR[0m in 3.78s]
[2025-05-25T17:43:29.028+0000] {utils.py:73} INFO - [0m17:43:29  1 of 6 ERROR creating sql incremental model STG.stg_campaigns .................. [[31mERROR[0m in 3.80s]
[2025-05-25T17:43:29.061+0000] {utils.py:73} INFO - [0m17:43:29  5 of 6 START sql incremental model STG.stg_pages ............................... [RUN]
[2025-05-25T17:43:29.074+0000] {utils.py:73} INFO - [0m17:43:29  6 of 6 START sql incremental model STG.stg_website_activity .................... [RUN]
[2025-05-25T17:43:29.987+0000] {utils.py:73} INFO - [0m17:43:29  3 of 6 ERROR creating sql incremental model STG.stg_form_fills ................. [[31mERROR[0m in 4.74s]
[2025-05-25T17:43:31.027+0000] {utils.py:73} INFO - [0m17:43:31  2 of 6 OK created sql incremental model STG.stg_contacts ....................... [[32mSUCCESS 1000[0m in 5.79s]
[2025-05-25T17:43:31.859+0000] {utils.py:73} INFO - [0m17:43:31  5 of 6 ERROR creating sql incremental model STG.stg_pages ...................... [[31mERROR[0m in 2.77s]
[2025-05-25T17:43:32.065+0000] {utils.py:73} INFO - [0m17:43:32  6 of 6 ERROR creating sql incremental model STG.stg_website_activity ........... [[31mERROR[0m in 2.98s]
[2025-05-25T17:43:33.010+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.016+0000] {utils.py:73} INFO - [0m17:43:33  Finished running 6 incremental models in 0 hours 0 minutes and 13.95 seconds (13.95s).
[2025-05-25T17:43:33.317+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.322+0000] {utils.py:73} INFO - [0m17:43:33  [31mCompleted with 5 errors, 0 partial successes, and 0 warnings:[0m
[2025-05-25T17:43:33.327+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.337+0000] {utils.py:73} INFO - [0m17:43:33    Database Error in model stg_forms (models/staging/stg_forms.sql)
[2025-05-25T17:43:33.342+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:43:33.345+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:43:33.349+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_forms.sql
[2025-05-25T17:43:33.352+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.359+0000] {utils.py:73} INFO - [0m17:43:33    Database Error in model stg_campaigns (models/staging/stg_campaigns.sql)
[2025-05-25T17:43:33.366+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:43:33.376+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:43:33.383+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_campaigns.sql
[2025-05-25T17:43:33.388+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.397+0000] {utils.py:73} INFO - [0m17:43:33    Database Error in model stg_form_fills (models/staging/stg_form_fills.sql)
[2025-05-25T17:43:33.403+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:43:33.409+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:43:33.416+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_form_fills.sql
[2025-05-25T17:43:33.425+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.434+0000] {utils.py:73} INFO - [0m17:43:33    Database Error in model stg_pages (models/staging/stg_pages.sql)
[2025-05-25T17:43:33.440+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:43:33.455+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:43:33.464+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_pages.sql
[2025-05-25T17:43:33.475+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.484+0000] {utils.py:73} INFO - [0m17:43:33    Database Error in model stg_website_activity (models/staging/stg_website_activity.sql)
[2025-05-25T17:43:33.499+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:43:33.503+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:43:33.508+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_website_activity.sql
[2025-05-25T17:43:33.512+0000] {utils.py:73} INFO - [0m17:43:33
[2025-05-25T17:43:33.517+0000] {utils.py:73} INFO - [0m17:43:33  Done. PASS=1 WARN=0 ERROR=5 SKIP=0 TOTAL=6
[2025-05-25T17:43:34.439+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 77, in run_dbt
    raise RuntimeError(f"dbt command failed with exit code {return_code}")
RuntimeError: dbt command failed with exit code 1
[2025-05-25T17:43:34.552+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=final_marketing_data_pipeline, task_id=dbt_run.dbt_run_staging, execution_date=20250525T162547, start_date=20250525T174210, end_date=20250525T174334
[2025-05-25T17:43:34.554+0000] {email_notification.py:55} WARNING - üìß Sending generic failure email [Airflow] Failure in final_marketing_data_pipeline.dbt_run.dbt_run_staging (Attempt 6/5)
[2025-05-25T17:43:34.581+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-05-25T17:43:34.583+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-05-25T17:43:36.894+0000] {email.py:281} INFO - Sent an alert email to ['yashbhawsar872@gmail.com']
[2025-05-25T17:43:38.607+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 131 for task dbt_run.dbt_run_staging (dbt command failed with exit code 1; 17937)
[2025-05-25T17:43:38.698+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-25T17:43:38.841+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
