[2025-05-25T16:33:55.838+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T16:33:55.859+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T16:33:55.860+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-25T16:33:55.891+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run.dbt_run_staging> on 2025-05-25 16:25:47.685943+00:00
[2025-05-25T16:33:55.904+0000] {standard_task_runner.py:60} INFO - Started process 16189 to run task
[2025-05-25T16:33:55.913+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_marketing_data_pipeline', 'dbt_run.dbt_run_staging', 'manual__2025-05-25T16:25:47.685943+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6fdb5nzb']
[2025-05-25T16:33:55.918+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask dbt_run.dbt_run_staging
[2025-05-25T16:33:56.060+0000] {task_command.py:423} INFO - Running <TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [running]> on host fe289fe396bd
[2025-05-25T16:33:56.335+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='final_marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run.dbt_run_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T16:25:47.685943+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T16:25:47.685943+00:00'
[2025-05-25T16:33:56.338+0000] {test.py:39} INFO - ‚ñ∂Ô∏è Starting task: Run staging models
[2025-05-25T16:33:56.379+0000] {utils.py:64} INFO - Running dbt command: cd /opt/dbt/marketing_pipeline && dbt run --models staging --vars '{"batch_date": "2025-05-25"}'
[2025-05-25T16:34:01.776+0000] {utils.py:73} INFO - [0m16:34:01  Running with dbt=1.9.4
[2025-05-25T16:34:04.607+0000] {utils.py:73} INFO - [0m16:34:04  Registered adapter: snowflake=1.9.4
[2025-05-25T16:34:10.757+0000] {utils.py:73} INFO - [0m16:34:10  Encountered an error:
[2025-05-25T16:34:10.761+0000] {utils.py:73} INFO - Parsing Error
[2025-05-25T16:34:10.766+0000] {utils.py:73} INFO - Invalid test config given in models/staging/schema.yml:
[2025-05-25T16:34:10.770+0000] {utils.py:73} INFO - test arguments must be a dict, got <class 'str'> (value session_duration >= 0)
[2025-05-25T16:34:10.774+0000] {utils.py:73} INFO - @: UnparsedModelUpdate(original_file_path='mode...ne)
[2025-05-25T16:34:11.670+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 77, in run_dbt
    raise RuntimeError(f"dbt command failed with exit code {return_code}")
RuntimeError: dbt command failed with exit code 2
[2025-05-25T16:34:11.759+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=final_marketing_data_pipeline, task_id=dbt_run.dbt_run_staging, execution_date=20250525T162547, start_date=20250525T163355, end_date=20250525T163411
[2025-05-25T16:34:11.760+0000] {taskinstance.py:1116} ERROR - Error when executing notify_failure callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 77, in run_dbt
    raise RuntimeError(f"dbt command failed with exit code {return_code}")
RuntimeError: dbt command failed with exit code 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1113, in _run_finished_callback
    callback(context)
TypeError: notify_failure() takes 0 positional arguments but 1 was given
[2025-05-25T16:34:11.800+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 124 for task dbt_run.dbt_run_staging (dbt command failed with exit code 2; 16189)
[2025-05-25T16:34:11.829+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-25T16:34:11.905+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
