[2025-05-25T17:36:01.907+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T17:36:01.946+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T17:36:01.947+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2025-05-25T17:36:02.844+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run.dbt_run_staging> on 2025-05-25 16:25:47.685943+00:00
[2025-05-25T17:36:02.871+0000] {standard_task_runner.py:60} INFO - Started process 17771 to run task
[2025-05-25T17:36:02.883+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_marketing_data_pipeline', 'dbt_run.dbt_run_staging', 'manual__2025-05-25T16:25:47.685943+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmphcienqnf']
[2025-05-25T17:36:02.889+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask dbt_run.dbt_run_staging
[2025-05-25T17:36:03.059+0000] {task_command.py:423} INFO - Running <TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [running]> on host fe289fe396bd
[2025-05-25T17:36:03.275+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='final_marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run.dbt_run_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T16:25:47.685943+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T16:25:47.685943+00:00'
[2025-05-25T17:36:03.278+0000] {test.py:39} INFO - ‚ñ∂Ô∏è Starting task: Run staging models
[2025-05-25T17:36:03.281+0000] {utils.py:64} INFO - Running dbt command: cd /opt/dbt/marketing_pipeline && dbt run --models staging --vars '{"batch_date": "2025-05-25"}'
[2025-05-25T17:36:21.739+0000] {utils.py:73} INFO - [0m17:36:21  Running with dbt=1.9.4
[2025-05-25T17:36:24.848+0000] {utils.py:73} INFO - [0m17:36:24  Registered adapter: snowflake=1.9.4
[2025-05-25T17:36:26.578+0000] {utils.py:73} INFO - [0m17:36:26  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-05-25T17:36:42.007+0000] {utils.py:73} INFO - [0m17:36:42  Found 12 models, 79 data tests, 6 sources, 479 macros
[2025-05-25T17:36:42.031+0000] {utils.py:73} INFO - [0m17:36:42
[2025-05-25T17:36:42.039+0000] {utils.py:73} INFO - [0m17:36:42  Concurrency: 4 threads (target='dev')
[2025-05-25T17:36:42.061+0000] {utils.py:73} INFO - [0m17:36:42
[2025-05-25T17:36:46.965+0000] {utils.py:73} INFO - [0m17:36:46  1 of 6 START sql incremental model STG.stg_campaigns ........................... [RUN]
[2025-05-25T17:36:47.031+0000] {utils.py:73} INFO - [0m17:36:47  3 of 6 START sql incremental model STG.stg_form_fills .......................... [RUN]
[2025-05-25T17:36:47.134+0000] {utils.py:73} INFO - [0m17:36:47  4 of 6 START sql incremental model STG.stg_forms ............................... [RUN]
[2025-05-25T17:36:47.280+0000] {utils.py:73} INFO - [0m17:36:47  2 of 6 START sql incremental model STG.stg_contacts ............................ [RUN]
[2025-05-25T17:36:49.796+0000] {utils.py:73} INFO - [0m17:36:49  2 of 6 ERROR creating sql incremental model STG.stg_contacts ................... [[31mERROR[0m in 2.44s]
[2025-05-25T17:36:49.926+0000] {utils.py:73} INFO - [0m17:36:49  5 of 6 START sql incremental model STG.stg_pages ............................... [RUN]
[2025-05-25T17:36:51.752+0000] {utils.py:73} INFO - [0m17:36:51  1 of 6 ERROR creating sql incremental model STG.stg_campaigns .................. [[31mERROR[0m in 4.51s]
[2025-05-25T17:36:51.770+0000] {utils.py:73} INFO - [0m17:36:51  6 of 6 START sql incremental model STG.stg_website_activity .................... [RUN]
[2025-05-25T17:36:52.078+0000] {utils.py:73} INFO - [0m17:36:52  3 of 6 ERROR creating sql incremental model STG.stg_form_fills ................. [[31mERROR[0m in 5.03s]
[2025-05-25T17:36:53.617+0000] {utils.py:73} INFO - [0m17:36:53  4 of 6 ERROR creating sql incremental model STG.stg_forms ...................... [[31mERROR[0m in 6.20s]
[2025-05-25T17:36:53.627+0000] {utils.py:73} INFO - [0m17:36:53  5 of 6 ERROR creating sql incremental model STG.stg_pages ...................... [[31mERROR[0m in 3.66s]
[2025-05-25T17:36:56.961+0000] {utils.py:73} INFO - [0m17:36:56  6 of 6 ERROR creating sql incremental model STG.stg_website_activity ........... [[31mERROR[0m in 5.18s]
[2025-05-25T17:36:58.003+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.075+0000] {utils.py:73} INFO - [0m17:36:58  Finished running 6 incremental models in 0 hours 0 minutes and 15.94 seconds (15.94s).
[2025-05-25T17:36:58.736+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.743+0000] {utils.py:73} INFO - [0m17:36:58  [31mCompleted with 6 errors, 0 partial successes, and 0 warnings:[0m
[2025-05-25T17:36:58.749+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.759+0000] {utils.py:73} INFO - [0m17:36:58    Database Error in model stg_contacts (models/staging/stg_contacts.sql)
[2025-05-25T17:36:58.771+0000] {utils.py:73} INFO - 000904 (42000): SQL compilation error: error line 15 at position 4
[2025-05-25T17:36:58.778+0000] {utils.py:73} INFO - invalid identifier 'PHONE'
[2025-05-25T17:36:58.791+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.806+0000] {utils.py:73} INFO - [0m17:36:58    Database Error in model stg_campaigns (models/staging/stg_campaigns.sql)
[2025-05-25T17:36:58.815+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:36:58.821+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:36:58.824+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_campaigns.sql
[2025-05-25T17:36:58.828+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.832+0000] {utils.py:73} INFO - [0m17:36:58    Database Error in model stg_form_fills (models/staging/stg_form_fills.sql)
[2025-05-25T17:36:58.837+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:36:58.840+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:36:58.842+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_form_fills.sql
[2025-05-25T17:36:58.845+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.848+0000] {utils.py:73} INFO - [0m17:36:58    Database Error in model stg_forms (models/staging/stg_forms.sql)
[2025-05-25T17:36:58.850+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:36:58.852+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:36:58.854+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_forms.sql
[2025-05-25T17:36:58.857+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.864+0000] {utils.py:73} INFO - [0m17:36:58    Database Error in model stg_pages (models/staging/stg_pages.sql)
[2025-05-25T17:36:58.871+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:36:58.878+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:36:58.885+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_pages.sql
[2025-05-25T17:36:58.896+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.903+0000] {utils.py:73} INFO - [0m17:36:58    Database Error in model stg_website_activity (models/staging/stg_website_activity.sql)
[2025-05-25T17:36:58.909+0000] {utils.py:73} INFO - 100090 (42P18): Duplicate row detected during DML action
[2025-05-25T17:36:58.913+0000] {utils.py:73} INFO - Row Values: [redacted]
[2025-05-25T17:36:58.921+0000] {utils.py:73} INFO - compiled code at target/run/marketing_pipeline/models/staging/stg_website_activity.sql
[2025-05-25T17:36:58.928+0000] {utils.py:73} INFO - [0m17:36:58
[2025-05-25T17:36:58.934+0000] {utils.py:73} INFO - [0m17:36:58  Done. PASS=0 WARN=0 ERROR=6 SKIP=0 TOTAL=6
[2025-05-25T17:37:00.347+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 77, in run_dbt
    raise RuntimeError(f"dbt command failed with exit code {return_code}")
RuntimeError: dbt command failed with exit code 1
[2025-05-25T17:37:00.418+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=final_marketing_data_pipeline, task_id=dbt_run.dbt_run_staging, execution_date=20250525T162547, start_date=20250525T173601, end_date=20250525T173700
[2025-05-25T17:37:00.499+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 130 for task dbt_run.dbt_run_staging (dbt command failed with exit code 1; 17771)
[2025-05-25T17:37:00.533+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-25T17:37:00.598+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
