[2025-05-25T16:28:29.919+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T16:28:29.941+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T16:28:29.942+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-25T16:28:29.977+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run.dbt_run_staging> on 2025-05-25 16:25:47.685943+00:00
[2025-05-25T16:28:29.989+0000] {standard_task_runner.py:60} INFO - Started process 16047 to run task
[2025-05-25T16:28:29.995+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_marketing_data_pipeline', 'dbt_run.dbt_run_staging', 'manual__2025-05-25T16:25:47.685943+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpwr8amkmn']
[2025-05-25T16:28:30.001+0000] {standard_task_runner.py:88} INFO - Job 123: Subtask dbt_run.dbt_run_staging
[2025-05-25T16:28:30.143+0000] {task_command.py:423} INFO - Running <TaskInstance: final_marketing_data_pipeline.dbt_run.dbt_run_staging manual__2025-05-25T16:25:47.685943+00:00 [running]> on host fe289fe396bd
[2025-05-25T16:28:30.363+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='final_marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run.dbt_run_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T16:25:47.685943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T16:25:47.685943+00:00'
[2025-05-25T16:28:30.368+0000] {test.py:39} INFO - ‚ñ∂Ô∏è Starting task: Run staging models
[2025-05-25T16:28:30.372+0000] {utils.py:64} INFO - Running dbt command: cd /opt/dbt/marketing_pipeline && dbt run --models staging --vars '{"batch_date": "2025-05-25"}'
[2025-05-25T16:28:37.546+0000] {utils.py:73} INFO - [0m16:28:37  Running with dbt=1.9.4
[2025-05-25T16:28:40.828+0000] {utils.py:73} INFO - [0m16:28:40  Registered adapter: snowflake=1.9.4
[2025-05-25T16:28:48.913+0000] {utils.py:73} INFO - [0m16:28:48  Encountered an error:
[2025-05-25T16:28:48.963+0000] {utils.py:73} INFO - Parsing Error
[2025-05-25T16:28:48.970+0000] {utils.py:73} INFO - Invalid test config given in models/staging/schema.yml:
[2025-05-25T16:28:48.987+0000] {utils.py:73} INFO - test arguments must be a dict, got <class 'str'> (value fill_date <= current_timestamp())
[2025-05-25T16:28:48.996+0000] {utils.py:73} INFO - @: UnparsedModelUpdate(original_file_path='mode...ne)
[2025-05-25T16:28:50.682+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 77, in run_dbt
    raise RuntimeError(f"dbt command failed with exit code {return_code}")
RuntimeError: dbt command failed with exit code 2
[2025-05-25T16:28:51.838+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=final_marketing_data_pipeline, task_id=dbt_run.dbt_run_staging, execution_date=20250525T162547, start_date=20250525T162829, end_date=20250525T162851
[2025-05-25T16:28:51.930+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 123 for task dbt_run.dbt_run_staging (dbt command failed with exit code 2; 16047)
[2025-05-25T16:28:52.036+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-25T16:28:52.190+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
