[2025-05-27T21:25:53.477+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.generate_and_validate_dims.validate_pages scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-27T21:25:53.527+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.generate_and_validate_dims.validate_pages scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-27T21:25:53.533+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-27T21:25:53.663+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_and_validate_dims.validate_pages> on 2025-05-24 00:00:00+00:00
[2025-05-27T21:25:53.725+0000] {standard_task_runner.py:60} INFO - Started process 341 to run task
[2025-05-27T21:25:53.845+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'generate_and_validate_dims.validate_pages', 'scheduled__2025-05-24T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmp7f9bukbw']
[2025-05-27T21:25:54.433+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask generate_and_validate_dims.validate_pages
[2025-05-27T21:25:55.090+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.generate_and_validate_dims.validate_pages scheduled__2025-05-24T00:00:00+00:00 [running]> on host 485388d78c3d
[2025-05-27T21:25:55.640+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='generate_and_validate_dims.validate_pages' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-24T00:00:00+00:00'
[2025-05-27T21:25:55.645+0000] {Marketing_Data_Pipeline.py:39} INFO - ▶️ Starting task: Validate Pages
[2025-05-27T21:25:55.672+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Marketing_Data_Pipeline.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 27, in wrapper
    result = func(*args, **kwargs)
  File "/opt/airflow/scripts/data_validation.py", line 217, in validate_pages_if_needed
    return _validate_generic(
  File "/opt/airflow/scripts/data_validation.py", line 79, in _validate_generic
    raise FileNotFoundError(f"{filename} not found")
FileNotFoundError: pages_2025-05-24.json not found
[2025-05-27T21:25:56.713+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Marketing_Data_Pipeline, task_id=generate_and_validate_dims.validate_pages, execution_date=20250524T000000, start_date=20250527T212553, end_date=20250527T212556
[2025-05-27T21:25:56.776+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task generate_and_validate_dims.validate_pages (pages_2025-05-24.json not found; 341)
[2025-05-27T21:25:56.839+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-27T21:25:57.160+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
